// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD12LX13M_fWmYmlQ9bNjR_sT50z5zCmqo',
    appId: '1:603627069667:web:548ed54a4f1e12a28ce5d6',
    messagingSenderId: '603627069667',
    projectId: 'flutter-firebase691',
    authDomain: 'flutter-firebase691.firebaseapp.com',
    storageBucket: 'flutter-firebase691.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAoN7MGIWFYqMyaox1ESCdNTmqYrTuVeg',
    appId: '1:603627069667:android:2938259d55f107fa8ce5d6',
    messagingSenderId: '603627069667',
    projectId: 'flutter-firebase691',
    storageBucket: 'flutter-firebase691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHf921sUj0CdhAlA-U4YvddEznAITuOuc',
    appId: '1:603627069667:ios:789ada7cdd19f7fb8ce5d6',
    messagingSenderId: '603627069667',
    projectId: 'flutter-firebase691',
    storageBucket: 'flutter-firebase691.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHf921sUj0CdhAlA-U4YvddEznAITuOuc',
    appId: '1:603627069667:ios:789ada7cdd19f7fb8ce5d6',
    messagingSenderId: '603627069667',
    projectId: 'flutter-firebase691',
    storageBucket: 'flutter-firebase691.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD12LX13M_fWmYmlQ9bNjR_sT50z5zCmqo',
    appId: '1:603627069667:web:3b170bdb6121d69c8ce5d6',
    messagingSenderId: '603627069667',
    projectId: 'flutter-firebase691',
    authDomain: 'flutter-firebase691.firebaseapp.com',
    storageBucket: 'flutter-firebase691.appspot.com',
  );
}
